### ISSUE TITLE
Feat: Improve the settings page.

### ISSUE THREAD

**Issue by 0xdevcollins** [GridApe/v1#27]
@Benjtalkshow Make the /Settings page Mobile Responsive and also ensure the flow is correct. maybe confirm with @ezeanyimhenry

**Comment by Benjtalkshow** [comment]
@ezeanyimhenry  
Whats the correct flow of this very page???

**Comment by ezeanyimhenry** [comment]
check figma - https://www.figma.com/design/Ni7TwQtYJSELLQgSDhoRRx/Edited-work(Gridape)?t=43x5Cy7bCfGVEABs-0

Settings have user Profile Update and Domains

**Comment by Benjtalkshow** [comment]
> check figma - https://www.figma.com/design/Ni7TwQtYJSELLQgSDhoRRx/Edited-work(Gridape)?t=43x5Cy7bCfGVEABs-0
> 
> Settings have user Profile Update and Domains @Benjtalkshow

Ok
